package com.lifechain.work.service;

import com.lifechain.common.enums.ErrorCodeEnum;
import com.lifechain.common.exception.BizException;
import com.lifechain.common.util.DateTimeUtil;
import com.lifechain.work.entity.CertificateEntity;
import com.lifechain.work.entity.ClaimApplicationEntity;
import com.lifechain.work.entity.WorkEntity;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;

/**
 * 证书PDF生成器
 */
@Slf4j
@Component
public class CertificatePdfGenerator {

    /**
     * 生成证书PDF字节数组
     */
    public byte[] generatePdf(CertificateEntity cert, ClaimApplicationEntity claim,
                              WorkEntity work, String creatorDid, LocalDateTime issueTime) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4, 60, 60, 80, 60);
            PdfWriter.getInstance(document, out);
            document.open();

            // 使用内置字体（支持ASCII），中文场景可替换为系统中文字体
            Font titleFont = new Font(Font.HELVETICA, 24, Font.BOLD);
            Font headerFont = new Font(Font.HELVETICA, 14, Font.BOLD);
            Font normalFont = new Font(Font.HELVETICA, 11, Font.NORMAL);
            Font smallFont = new Font(Font.HELVETICA, 9, Font.NORMAL, java.awt.Color.GRAY);

            // 标题
            Paragraph title = new Paragraph("Digital Rights Certificate", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(30);
            document.add(title);

            // 分割线
            Paragraph line = new Paragraph("─".repeat(60), smallFont);
            line.setAlignment(Element.ALIGN_CENTER);
            line.setSpacingAfter(20);
            document.add(line);

            // 证书编号
            addField(document, "Certificate No", cert.getCertNo(), headerFont, normalFont);
            addField(document, "Version", String.valueOf(cert.getVersion()), headerFont, normalFont);

            // 作品信息
            document.add(new Paragraph(" "));
            addField(document, "Work No", work.getWorkNo(), headerFont, normalFont);
            addField(document, "Work Title", work.getTitle(), headerFont, normalFont);
            addField(document, "Work Type", work.getWorkType(), headerFont, normalFont);

            // 确权信息
            document.add(new Paragraph(" "));
            addField(document, "Claim No", claim.getClaimNo(), headerFont, normalFont);
            addField(document, "Creator DID", creatorDid != null ? creatorDid : "N/A", headerFont, normalFont);

            // 哈希信息
            document.add(new Paragraph(" "));
            addField(document, "File Hash", nvl(work.getFileHash()), headerFont, normalFont);
            addField(document, "Meta Hash", nvl(work.getMetaHash()), headerFont, normalFont);
            addField(document, "Summary Hash", nvl(claim.getSummaryHash()), headerFont, normalFont);
            addField(document, "Certificate Hash", nvl(cert.getCertHash()), headerFont, normalFont);

            // 链上信息
            document.add(new Paragraph(" "));
            addField(document, "Tx Hash", nvl(claim.getTxHash()), headerFont, normalFont);
            addField(document, "Block Height",
                    claim.getBlockHeight() != null ? claim.getBlockHeight().toString() : "N/A",
                    headerFont, normalFont);

            // 时间信息
            document.add(new Paragraph(" "));
            addField(document, "Issue Time", DateTimeUtil.formatUtc(issueTime), headerFont, normalFont);
            addField(document, "Expire Time", DateTimeUtil.formatUtc(issueTime.plusYears(10)), headerFont, normalFont);

            // 底部说明
            document.add(new Paragraph(" "));
            Paragraph footer = new Paragraph(
                    "This certificate is generated by AIGC-LifeChain platform. " +
                    "The on-chain data can be verified via blockchain explorer.", smallFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            footer.setSpacingBefore(30);
            document.add(footer);

            document.close();
            return out.toByteArray();
        } catch (Exception e) {
            log.error("证书PDF生成失败, certNo={}", cert.getCertNo(), e);
            throw new BizException(ErrorCodeEnum.CERT_GENERATE_FAILED, "证书PDF生成失败", e);
        }
    }

    private void addField(Document doc, String label, String value,
                          Font labelFont, Font valueFont) throws DocumentException {
        Paragraph p = new Paragraph();
        p.add(new Chunk(label + ": ", labelFont));
        p.add(new Chunk(value != null ? value : "N/A", valueFont));
        p.setSpacingAfter(6);
        doc.add(p);
    }

    private String nvl(String value) {
        return value != null ? value : "N/A";
    }
}
