-- =============================================================
-- V4: Trade & License Domain
-- =============================================================

CREATE TABLE IF NOT EXISTS `license_template` (
    `id`                BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `template_name`     VARCHAR(128) NOT NULL               COMMENT '模板名称',
    `template_code`     VARCHAR(64)  NOT NULL               COMMENT '模板编码',
    `license_type`      VARCHAR(30)  NOT NULL               COMMENT '授权类型(PERSONAL_USE/COMMERCIAL_USE/EXCLUSIVE)',
    `scope_description` TEXT                  DEFAULT NULL  COMMENT '范围描述',
    `duration_days`     INT                   DEFAULT NULL  COMMENT '有效天数',
    `price_amount`      BIGINT       NOT NULL               COMMENT '价格（分）',
    `currency`          VARCHAR(10)  NOT NULL DEFAULT 'CNY' COMMENT '币种',
    `status`            VARCHAR(20)  NOT NULL               COMMENT '状态(ACTIVE/INACTIVE)',
    `description`       VARCHAR(512)          DEFAULT NULL  COMMENT '描述',
    `deleted_flag`      TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `created_at`        DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`        DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_template_code` (`template_code`),
    KEY `idx_license_type` (`license_type`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='授权模板表';

CREATE TABLE IF NOT EXISTS `work_listing` (
    `id`                  BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `listing_no`          VARCHAR(64)  NOT NULL               COMMENT '上架编号',
    `work_id`             BIGINT       NOT NULL               COMMENT '作品ID',
    `work_no`             VARCHAR(64)  NOT NULL               COMMENT '作品编号',
    `creator_account_id`  BIGINT       NOT NULL               COMMENT '创作者账户ID',
    `license_template_id` BIGINT                DEFAULT NULL  COMMENT '授权模板ID',
    `license_type`        VARCHAR(30)  NOT NULL               COMMENT '授权类型',
    `price_amount`        BIGINT       NOT NULL               COMMENT '价格（分）',
    `currency`            VARCHAR(10)  NOT NULL DEFAULT 'CNY' COMMENT '币种',
    `status`              VARCHAR(30)  NOT NULL               COMMENT '上架状态(PENDING_REVIEW/LISTED/UNLISTED/REJECTED/FROZEN)',
    `review_status`       VARCHAR(20)           DEFAULT NULL  COMMENT '审核状态',
    `reviewer_id`         BIGINT                DEFAULT NULL  COMMENT '审核人ID',
    `review_comment`      VARCHAR(512)          DEFAULT NULL  COMMENT '审核意见',
    `list_time`           DATETIME              DEFAULT NULL  COMMENT '上架时间(UTC)',
    `unlist_time`         DATETIME              DEFAULT NULL  COMMENT '下架时间(UTC)',
    `scope_description`   TEXT                  DEFAULT NULL  COMMENT '范围描述',
    `duration_days`       INT                   DEFAULT NULL  COMMENT '有效天数',
    `version`             INT          NOT NULL DEFAULT 0     COMMENT '乐观锁版本号',
    `deleted_flag`        TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `created_at`          DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`          DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_listing_no` (`listing_no`),
    KEY `idx_work_id` (`work_id`),
    KEY `idx_work_no` (`work_no`),
    KEY `idx_creator_account_id` (`creator_account_id`),
    KEY `idx_status` (`status`),
    KEY `idx_license_type` (`license_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='作品上架表';

CREATE TABLE IF NOT EXISTS `trade_order` (
    `id`                  BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `order_no`            VARCHAR(64)  NOT NULL               COMMENT '订单编号',
    `work_id`             BIGINT       NOT NULL               COMMENT '作品ID',
    `work_no`             VARCHAR(64)  NOT NULL               COMMENT '作品编号',
    `listing_id`          BIGINT       NOT NULL               COMMENT '上架记录ID',
    `listing_no`          VARCHAR(64)  NOT NULL               COMMENT '上架编号',
    `buyer_account_id`    BIGINT       NOT NULL               COMMENT '买方账户ID',
    `buyer_subject_id`    BIGINT       NOT NULL               COMMENT '买方主体ID',
    `creator_account_id`  BIGINT       NOT NULL               COMMENT '创作者账户ID',
    `creator_subject_id`  BIGINT       NOT NULL               COMMENT '创作者主体ID',
    `order_status`        VARCHAR(30)  NOT NULL               COMMENT '订单状态',
    `license_type`        VARCHAR(30)  NOT NULL               COMMENT '授权类型',
    `price_amount`        BIGINT       NOT NULL               COMMENT '原价（分）',
    `pay_amount`          BIGINT       NOT NULL               COMMENT '实付金额（分）',
    `currency`            VARCHAR(10)  NOT NULL DEFAULT 'CNY' COMMENT '币种',
    `pay_channel`         VARCHAR(20)           DEFAULT NULL  COMMENT '支付渠道',
    `pay_status`          VARCHAR(20)           DEFAULT NULL  COMMENT '支付状态',
    `expire_time`         DATETIME              DEFAULT NULL  COMMENT '订单过期时间(UTC)',
    `pay_time`            DATETIME              DEFAULT NULL  COMMENT '支付时间(UTC)',
    `complete_time`       DATETIME              DEFAULT NULL  COMMENT '完成时间(UTC)',
    `cancel_time`         DATETIME              DEFAULT NULL  COMMENT '取消时间(UTC)',
    `cancel_reason`       VARCHAR(512)          DEFAULT NULL  COMMENT '取消原因',
    `request_id`          VARCHAR(64)           DEFAULT NULL  COMMENT '幂等ID',
    `version`             INT          NOT NULL DEFAULT 0     COMMENT '乐观锁版本号',
    `deleted_flag`        TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `created_at`          DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`          DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_work_id` (`work_id`),
    KEY `idx_listing_id` (`listing_id`),
    KEY `idx_buyer_account_id` (`buyer_account_id`),
    KEY `idx_creator_account_id` (`creator_account_id`),
    KEY `idx_order_status` (`order_status`),
    KEY `idx_pay_status` (`pay_status`),
    KEY `idx_request_id` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='交易订单表';

CREATE TABLE IF NOT EXISTS `trade_order_snapshot` (
    `id`            BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `order_id`      BIGINT       NOT NULL               COMMENT '订单ID',
    `order_no`      VARCHAR(64)  NOT NULL               COMMENT '订单编号',
    `snapshot_type` VARCHAR(30)  NOT NULL               COMMENT '快照类型(WORK_INFO/LISTING_INFO/SETTLE_RULE)',
    `snapshot_data` TEXT         NOT NULL               COMMENT '快照数据(JSON)',
    `snapshot_hash` VARCHAR(128)          DEFAULT NULL  COMMENT '快照哈希',
    `snapshot_time` DATETIME     NOT NULL               COMMENT '快照时间(UTC)',
    `deleted_flag`  TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `created_at`    DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`    DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_snapshot_type` (`snapshot_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='交易订单快照表';

CREATE TABLE IF NOT EXISTS `payment_record` (
    `id`               BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `payment_no`       VARCHAR(64)  NOT NULL               COMMENT '支付编号',
    `order_id`         BIGINT       NOT NULL               COMMENT '订单ID',
    `order_no`         VARCHAR(64)  NOT NULL               COMMENT '订单编号',
    `pay_channel`      VARCHAR(20)  NOT NULL               COMMENT '支付渠道(WECHAT_PAY/ALIPAY)',
    `pay_status`       VARCHAR(20)  NOT NULL               COMMENT '支付状态',
    `pay_amount`       BIGINT       NOT NULL               COMMENT '支付金额（分）',
    `currency`         VARCHAR(10)  NOT NULL DEFAULT 'CNY' COMMENT '币种',
    `third_trade_no`   VARCHAR(128)          DEFAULT NULL  COMMENT '第三方交易号',
    `prepay_id`        VARCHAR(128)          DEFAULT NULL  COMMENT '预支付ID',
    `callback_raw_ref` VARCHAR(512)          DEFAULT NULL  COMMENT '回调原始报文索引',
    `pay_time`         DATETIME              DEFAULT NULL  COMMENT '支付时间(UTC)',
    `callback_time`    DATETIME              DEFAULT NULL  COMMENT '回调时间(UTC)',
    `expire_time`      DATETIME              DEFAULT NULL  COMMENT '过期时间(UTC)',
    `fail_reason`      VARCHAR(512)          DEFAULT NULL  COMMENT '失败原因',
    `request_id`       VARCHAR(64)           DEFAULT NULL  COMMENT '幂等ID',
    `deleted_flag`     TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `created_at`       DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`       DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_payment_no` (`payment_no`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_pay_channel` (`pay_channel`),
    KEY `idx_pay_status` (`pay_status`),
    KEY `idx_third_trade_no` (`third_trade_no`),
    KEY `idx_request_id` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='支付记录表';

CREATE TABLE IF NOT EXISTS `license_record` (
    `id`                   BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `license_no`           VARCHAR(64)  NOT NULL               COMMENT '授权编号',
    `order_id`             BIGINT       NOT NULL               COMMENT '订单ID',
    `order_no`             VARCHAR(64)  NOT NULL               COMMENT '订单编号',
    `work_id`              BIGINT       NOT NULL               COMMENT '作品ID',
    `work_no`              VARCHAR(64)  NOT NULL               COMMENT '作品编号',
    `licensor_account_id`  BIGINT       NOT NULL               COMMENT '授权方账户ID',
    `licensee_account_id`  BIGINT       NOT NULL               COMMENT '被授权方账户ID',
    `license_type`         VARCHAR(30)  NOT NULL               COMMENT '授权类型',
    `license_status`       VARCHAR(30)  NOT NULL               COMMENT '授权状态',
    `chain_status`         VARCHAR(30)  NOT NULL DEFAULT ''    COMMENT '链上状态',
    `scope_description`    TEXT                  DEFAULT NULL  COMMENT '范围描述',
    `effective_time`       DATETIME              DEFAULT NULL  COMMENT '生效时间(UTC)',
    `expire_time`          DATETIME              DEFAULT NULL  COMMENT '到期时间(UTC)',
    `license_hash`         VARCHAR(128)          DEFAULT NULL  COMMENT '授权哈希',
    `tx_hash`              VARCHAR(128)          DEFAULT NULL  COMMENT '交易哈希',
    `block_height`         BIGINT                DEFAULT NULL  COMMENT '区块高度',
    `terminate_time`       DATETIME              DEFAULT NULL  COMMENT '终止时间(UTC)',
    `terminate_reason`     VARCHAR(512)          DEFAULT NULL  COMMENT '终止原因',
    `request_id`           VARCHAR(64)           DEFAULT NULL  COMMENT '幂等ID',
    `deleted_flag`         TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `created_at`           DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`           DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_license_no` (`license_no`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_work_id` (`work_id`),
    KEY `idx_licensor_account_id` (`licensor_account_id`),
    KEY `idx_licensee_account_id` (`licensee_account_id`),
    KEY `idx_license_status` (`license_status`),
    KEY `idx_chain_status` (`chain_status`),
    KEY `idx_request_id` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='授权记录表';

CREATE TABLE IF NOT EXISTS `refund_record` (
    `id`              BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `refund_no`       VARCHAR(64)  NOT NULL               COMMENT '退款编号',
    `order_id`        BIGINT       NOT NULL               COMMENT '订单ID',
    `order_no`        VARCHAR(64)  NOT NULL               COMMENT '订单编号',
    `payment_id`      BIGINT       NOT NULL               COMMENT '支付记录ID',
    `payment_no`      VARCHAR(64)  NOT NULL               COMMENT '支付编号',
    `pay_channel`     VARCHAR(20)  NOT NULL               COMMENT '原支付渠道',
    `refund_amount`   BIGINT       NOT NULL               COMMENT '退款金额（分）',
    `currency`        VARCHAR(10)  NOT NULL DEFAULT 'CNY' COMMENT '币种',
    `refund_status`   VARCHAR(20)  NOT NULL               COMMENT '退款状态(PENDING/SUCCESS/FAILED)',
    `refund_reason`   VARCHAR(512)          DEFAULT NULL  COMMENT '退款原因',
    `reason_code`     VARCHAR(64)           DEFAULT NULL  COMMENT '原因码',
    `third_refund_no` VARCHAR(128)          DEFAULT NULL  COMMENT '渠道退款流水号',
    `apply_time`      DATETIME     NOT NULL               COMMENT '申请时间(UTC)',
    `complete_time`   DATETIME              DEFAULT NULL  COMMENT '完成时间(UTC)',
    `fail_reason`     VARCHAR(512)          DEFAULT NULL  COMMENT '失败原因',
    `operator_id`     BIGINT                DEFAULT NULL  COMMENT '操作人ID',
    `request_id`      VARCHAR(64)           DEFAULT NULL  COMMENT '幂等ID',
    `deleted_flag`    TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `created_at`      DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`      DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_refund_no` (`refund_no`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_payment_id` (`payment_id`),
    KEY `idx_refund_status` (`refund_status`),
    KEY `idx_third_refund_no` (`third_refund_no`),
    KEY `idx_request_id` (`request_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='退款记录表';
