-- =============================================================
-- V6: Regulator, Risk, Freeze, Dispute Domain
-- =============================================================

CREATE TABLE `risk_event` (
    `id`               BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `risk_no`          VARCHAR(64)  NOT NULL               COMMENT '风险编号',
    `target_type`      VARCHAR(30)  NOT NULL               COMMENT '目标类型',
    `target_id`        BIGINT       NOT NULL               COMMENT '目标ID',
    `target_no`        VARCHAR(64)           DEFAULT NULL  COMMENT '目标编号',
    `status`           VARCHAR(30)  NOT NULL               COMMENT '风险状态',
    `risk_level`       VARCHAR(20)  NOT NULL               COMMENT '风险等级(LOW/MEDIUM/HIGH/CRITICAL)',
    `risk_type`        VARCHAR(30)  NOT NULL               COMMENT '风险类型',
    `risk_description` TEXT                  DEFAULT NULL  COMMENT '风险描述',
    `reporter_id`      BIGINT                DEFAULT NULL  COMMENT '报告人ID',
    `reporter_role`    VARCHAR(30)           DEFAULT NULL  COMMENT '报告人角色',
    `report_time`      DATETIME              DEFAULT NULL  COMMENT '报告时间(UTC)',
    `reason_code`      VARCHAR(64)           DEFAULT NULL  COMMENT '原因码',
    `result_summary`   VARCHAR(512)          DEFAULT NULL  COMMENT '结果摘要',
    `resolve_time`     DATETIME              DEFAULT NULL  COMMENT '解决时间(UTC)',
    `deleted_flag`     TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `created_at`       DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`       DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_risk_no` (`risk_no`),
    KEY `idx_target_type_id` (`target_type`, `target_id`),
    KEY `idx_target_no` (`target_no`),
    KEY `idx_status` (`status`),
    KEY `idx_risk_level` (`risk_level`),
    KEY `idx_risk_type` (`risk_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='风险事件表';

CREATE TABLE `freeze_record` (
    `id`               BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `freeze_no`        VARCHAR(64)  NOT NULL               COMMENT '冻结编号',
    `target_type`      VARCHAR(30)  NOT NULL               COMMENT '目标类型',
    `target_id`        BIGINT       NOT NULL               COMMENT '目标ID',
    `target_no`        VARCHAR(64)           DEFAULT NULL  COMMENT '目标编号',
    `previous_target_status` VARCHAR(30)     DEFAULT NULL  COMMENT '冻结前目标状态快照',
    `freeze_status`    VARCHAR(30)  NOT NULL               COMMENT '冻结状态',
    `freeze_mode`      VARCHAR(30)  NOT NULL               COMMENT '冻结模式(REVIEW_REQUIRED/REGULATOR_DIRECT)',
    `review_status`    VARCHAR(20)           DEFAULT NULL  COMMENT '审核状态',
    `freeze_reason`    VARCHAR(512)          DEFAULT NULL  COMMENT '冻结原因',
    `reason_code`      VARCHAR(64)           DEFAULT NULL  COMMENT '原因码',
    `apply_user_id`    BIGINT       NOT NULL               COMMENT '申请人ID',
    `apply_role`       VARCHAR(30)           DEFAULT NULL  COMMENT '申请人角色',
    `apply_time`       DATETIME     NOT NULL               COMMENT '申请时间(UTC)',
    `approve_user_id`  BIGINT                DEFAULT NULL  COMMENT '审批人ID',
    `approve_time`     DATETIME              DEFAULT NULL  COMMENT '审批时间(UTC)',
    `effective_time`   DATETIME              DEFAULT NULL  COMMENT '生效时间(UTC)',
    `unfreeze_reason`  VARCHAR(512)          DEFAULT NULL  COMMENT '解冻原因',
    `unfreeze_time`    DATETIME              DEFAULT NULL  COMMENT '解冻时间(UTC)',
    `urgent_basis_no`  VARCHAR(128)          DEFAULT NULL  COMMENT '紧急依据编号',
    `chain_status`     VARCHAR(30)  NOT NULL DEFAULT ''    COMMENT '链上状态',
    `tx_hash`          VARCHAR(128)          DEFAULT NULL  COMMENT '交易哈希',
    `block_height`     BIGINT                DEFAULT NULL  COMMENT '区块高度',
    `deleted_flag`     TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `version`          INT          NOT NULL DEFAULT 0     COMMENT '乐观锁版本号',
    `created_at`       DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`       DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_freeze_no` (`freeze_no`),
    KEY `idx_target_type_id` (`target_type`, `target_id`),
    KEY `idx_target_no` (`target_no`),
    KEY `idx_freeze_status` (`freeze_status`),
    KEY `idx_freeze_mode` (`freeze_mode`),
    KEY `idx_apply_user_id` (`apply_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='冻结记录表';

CREATE TABLE `regulator_report` (
    `id`              BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `report_no`       VARCHAR(64)  NOT NULL               COMMENT '报告编号',
    `report_type`     VARCHAR(30)  NOT NULL               COMMENT '报告类型',
    `report_title`    VARCHAR(256) NOT NULL               COMMENT '报告标题',
    `report_content`  TEXT                  DEFAULT NULL  COMMENT '报告内容',
    `report_file_url` VARCHAR(512)          DEFAULT NULL  COMMENT '报告文件地址',
    `generator_id`    BIGINT                DEFAULT NULL  COMMENT '生成人ID',
    `status`          VARCHAR(20)  NOT NULL               COMMENT '状态(DRAFT/GENERATING/COMPLETED/FAILED)',
    `generate_time`   DATETIME              DEFAULT NULL  COMMENT '生成时间(UTC)',
    `summary_hash`    VARCHAR(128)          DEFAULT NULL  COMMENT '摘要哈希',
    `chain_status`    VARCHAR(30)  NOT NULL DEFAULT ''    COMMENT '链上状态',
    `tx_hash`         VARCHAR(128)          DEFAULT NULL  COMMENT '交易哈希',
    `block_height`    BIGINT                DEFAULT NULL  COMMENT '区块高度',
    `deleted_flag`    TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `created_at`      DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`      DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_report_no` (`report_no`),
    KEY `idx_report_type` (`report_type`),
    KEY `idx_status` (`status`),
    KEY `idx_generator_id` (`generator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='监管报告表';

CREATE TABLE `dispute_case` (
    `id`                     BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `case_no`                VARCHAR(64)  NOT NULL               COMMENT '争议案件编号',
    `order_id`               BIGINT                DEFAULT NULL  COMMENT '订单ID',
    `order_no`               VARCHAR(64)           DEFAULT NULL  COMMENT '订单编号',
    `work_id`                BIGINT                DEFAULT NULL  COMMENT '作品ID',
    `work_no`                VARCHAR(64)           DEFAULT NULL  COMMENT '作品编号',
    `applicant_account_id`   BIGINT       NOT NULL               COMMENT '申请人账户ID',
    `respondent_account_id`  BIGINT       NOT NULL               COMMENT '被申请人账户ID',
    `dispute_type`           VARCHAR(30)  NOT NULL               COMMENT '争议类型',
    `status`                 VARCHAR(30)  NOT NULL               COMMENT '争议状态',
    `description`            TEXT                  DEFAULT NULL  COMMENT '争议描述',
    `submit_time`            DATETIME              DEFAULT NULL  COMMENT '提交时间(UTC)',
    `accept_time`            DATETIME              DEFAULT NULL  COMMENT '受理时间(UTC)',
    `close_time`             DATETIME              DEFAULT NULL  COMMENT '结案时间(UTC)',
    `result_summary`         VARCHAR(512)          DEFAULT NULL  COMMENT '结果摘要',
    `reason_code`            VARCHAR(64)           DEFAULT NULL  COMMENT '原因码',
    `chain_status`           VARCHAR(30)  NOT NULL DEFAULT ''    COMMENT '链上状态',
    `tx_hash`                VARCHAR(128)          DEFAULT NULL  COMMENT '交易哈希',
    `block_height`           BIGINT                DEFAULT NULL  COMMENT '区块高度',
    `deleted_flag`           TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `version`                INT          NOT NULL DEFAULT 0     COMMENT '乐观锁版本号',
    `created_at`             DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`             DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_case_no` (`case_no`),
    KEY `idx_order_id` (`order_id`),
    KEY `idx_work_id` (`work_id`),
    KEY `idx_applicant_account_id` (`applicant_account_id`),
    KEY `idx_respondent_account_id` (`respondent_account_id`),
    KEY `idx_dispute_type` (`dispute_type`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='争议案件表';

CREATE TABLE `dispute_evidence` (
    `id`                   BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `case_id`              BIGINT       NOT NULL               COMMENT '争议案件ID',
    `case_no`              VARCHAR(64)  NOT NULL               COMMENT '争议案件编号',
    `submitter_account_id` BIGINT       NOT NULL               COMMENT '提交人账户ID',
    `evidence_type`        VARCHAR(30)  NOT NULL               COMMENT '证据类型',
    `evidence_description` VARCHAR(512)          DEFAULT NULL  COMMENT '证据描述',
    `file_url`             VARCHAR(512)          DEFAULT NULL  COMMENT '文件地址',
    `file_hash`            VARCHAR(128)          DEFAULT NULL  COMMENT '文件哈希',
    `submit_time`          DATETIME     NOT NULL               COMMENT '提交时间(UTC)',
    `deleted_flag`         TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `created_at`           DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`           DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    KEY `idx_case_id` (`case_id`),
    KEY `idx_case_no` (`case_no`),
    KEY `idx_submitter_account_id` (`submitter_account_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='争议证据表';

CREATE TABLE `dispute_process_record` (
    `id`            BIGINT       NOT NULL               COMMENT '主键（雪花ID）',
    `case_id`       BIGINT       NOT NULL               COMMENT '争议案件ID',
    `case_no`       VARCHAR(64)  NOT NULL               COMMENT '争议案件编号',
    `operator_id`   BIGINT       NOT NULL               COMMENT '操作人ID',
    `action`        VARCHAR(30)  NOT NULL               COMMENT '处理动作',
    `action_result` VARCHAR(30)           DEFAULT NULL  COMMENT '处理结果',
    `comment`       VARCHAR(512)          DEFAULT NULL  COMMENT '处理意见',
    `reason_code`   VARCHAR(64)           DEFAULT NULL  COMMENT '原因码',
    `process_time`  DATETIME     NOT NULL               COMMENT '处理时间(UTC)',
    `deleted_flag`  TINYINT      NOT NULL DEFAULT 0     COMMENT '删除标记 0-未删除 1-已删除',
    `created_at`    DATETIME     NOT NULL               COMMENT '创建时间(UTC)',
    `updated_at`    DATETIME     NOT NULL               COMMENT '更新时间(UTC)',
    PRIMARY KEY (`id`),
    KEY `idx_case_id` (`case_id`),
    KEY `idx_case_no` (`case_no`),
    KEY `idx_operator_id` (`operator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='争议处理记录表';
